@startuml Обработка заявки на кредит
    start
    :Система принимает заявку на кредит;
    :Ауитентифицирует пользователя;
    if (Пользователь аутентифицирован?) then (да)
        :Проверяет данные заявки на кредит;
        if (Данные заявки корректны?) then (да)
            :Обогащает и подготовливает данные пользователя;
            :Создает экземпляр заявки на кредит (Decision Request);
        else (нет)
            :Отклоняет заявку на кредит;
            stop
        endif
    else (нет)
        :Отклоняет заявку на кредит;
        stop
    endif
    
   :Выполняет проверку стоп-факторов;

    if (Стоп-факторы обнаружены?) then (Да)
        :Отклоняет заявку на кредит;
        stop
    else (Нет)
        :Рассчитывает скоринговый балл и вероятность дефолта (PD);
        :Применяет активную версию кредитной политики;
        :Формирует Reason Codes;
        :Генерирует человекочитаемое объяснение;

        if (Решение = Refer) then
            :Передает заявку на ручной андеррайтинг;
        elseif (Решение = Counter-offer) then
            :Формирует альтернативные условия;
        elseif (Решение = Approve / Decline) then
        endif
        
        :Сохраняет результаты в аудит;
        :Возвращает решение кредитору;
        stop

    endif
@enduml