@startuml Обработка заявки на кредит
    |Кредитор|
    start
    :Отправляет заявку на кредит в систему;

    |Скоринговая платформа|
    :Принимает заявку на кредит;
    :Ауитентифицирует пользователя;
    if (Пользователь аутентифицирован?) then (да)
        :Проверяет данные заявки на кредит;
        if (Данные заявки корректны?) then (да)

            :Создает экземпляр заявки на кредит (Decision Request);
            :Выполняет проверку стоп-факторов;

            if (Стоп-факторы обнаружены?) then (Да)
                :Принимает решение Decline;
                :Формирует Reason Codes;
                :Генерирует объяснение;
                :Формирует событие для сохранения аудита;
                :Возвращает решение кредитору;
                stop
            else (Нет)
                fork

                    repeat
                        :Запрашивает и нормализует данные через DaData;
                    repeat while (Сервис DaData недоступен? && Лимит попыток не превышен?) is (Да)

                    if (Данные успешно получены?) then (Нет)
                        :Логирует недоступность сервиса DaData;
                    else (Да)    
                    endif

                fork again

                    repeat
                        :Запрашивает географические признаки через Яндекс Геокодер;
                    repeat while (Сервис Геокодера недоступен? && Лимит попыток не превышен?) is (Да)

                    if (Данные успешно получены?) then (Нет)
                        :Логирует недоступность сервиса Геокодера;
                    else (Да)    
                    endif

                fork again

                    repeat
                        :Запрашивает кредитную историю в БКИ;
                    repeat while (Сервис БКИ недоступен? && Лимит попыток не превышен?) is (Да)

                    if (Данные успешно получены?) then (Нет)
                        :Логирует недоступность сервиса БКИ;
                    else (Да)
                    endif

                fork again

                    repeat
                        :Запрашивает сведения об исполнительных производствах в ФССП;
                    repeat while (Сервис ФССП недоступен? && Лимит попыток не превышен?) is (Да)

                    if (Данные успешно получены?) then (Нет)
                        :Логирует недоступность сервиса ФССП;
                    else (Да)
                    endif

                end fork
            endif
            :Заполняет экземпляр заявки на кредит (Decision Request) полученными данными;

            if (Отсутствуют критические данные?) then (Да)
                :Принимает решение Refer;
                :Формирует Reason Codes;
                :Генерирует объяснение;
                :Формирует событие для сохранения аудита;
                :Возвращает решение кредитору;
                stop
            else (Нет)    
        endif

        else (нет)
            :Отклоняет заявку на кредит;
            stop
        endif
    else (нет)
        :Отклоняет заявку на кредит;
        stop
    endif
    
   :Выполняет проверку стоп-факторов;

    
    :Рассчитывает скоринговый балл и вероятность дефолта (PD);
    :Применяет активную версию кредитной политики;
    :Формирует решение по заявке на кредит (Approve, Refer, Decline, Counter-offer);

    if (Решение = Counter-offer) then
        :Формирует альтернативные условия;
    elseif (Остальные решения) then
        :Продолжает обработку;
    endif

    :Формирует Reason Codes;
    :Генерирует объяснение;
    :Формирует событие для сохранения аудита;
    :Возвращает решение кредитору;
    end

@enduml